fixtures:
  symlinks:
    perforce: "#{source_dir}"
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    yumrepo_core:
      repo: "git://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      ref: "1.0.4"